# Site
repository: parkje0927/parkje0927.github.io
# favicon: images/favicon.ico

# Content configuration version
# version: 2

# Personal info
name: 박정현
title: Java 백엔드 엔지니어
email: parkje09270@gmail.com
website: https://jjungdev.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: parkje0927
# stackoverflow_username: "00000001"
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# youtube_username: globalmtb

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  다양한 기술에 관심을 가지며 알고리즘을 연구하며 접목시켜 나가 지속적으로 고민하는 사람이 되고 싶습니다. 
  경제학을 복수전공하면서 여러 수식과 모형을 기반으로 거시 경제를 예측하는 금융 과목에 관심이 많았고, ‘데이터 경제’ 라는 새로운 분야를 알게 되었습니다. 이를 더 배우려고 대학원을 가게 되었는데 접근 방법론 중에서 컴퓨터와 융합하는 방법을 알게 되어 관심을 갖게 되었습니다. 
  알고리즘 문제를 풀어보며 컴퓨터 전반에 대한 이해의 필요성을 느꼈고, 전공 공부를 스스로 진행하며 정보처리기사를 준비하였습니다. 또한 데이터를 더 이해하기 위해 백엔드 분야에 대해 알아보며 웹 개발 과정을 수강하였고 수강 이후 실제 실무에서 쓰는 기술을 배우고 싶어 Spring에 대해서 스스로 학습을 진행했습니다. 또한 최신 기술 동향인 AI 기술을 배울 필요성을 느껴 국비 과정을 수강 하였고, 현재 백엔드 업무를 진행하며 지속적으로 관련 기술들을 스터디 하고 있습니다. 최신 기술 스택을 더 배워 나가며 기술이 인간에게 더 가까워질 수 있도록 서비스 개발을 하고 싶습니다.
  
  - 학력 사항
    - 2014.03 ~ 2019.02 숙명여자대학교 행정/경제학 졸업
    - 2011.03 ~ 2014.02 하남고등학교 졸업

# content:

# Skill Section
# skill_title: Skill

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: More


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
